import type { Metadata } from "next";
import {
  Shalimar,
  Crimson_Text,
  League_Spartan,
  Montserrat,
} from "next/font/google";
import "./globals.scss";

const shalimarSans = Shalimar({
  variable: "--font-shalimar-sans",
  subsets: ["latin"],
  weight: "400",
});
const crimsonTextSans = Crimson_Text({
  variable: "--font-crimson-text-sans",
  subsets: ["latin"],
  weight: "600",
});
const leagueSpartanSans = League_Spartan({
  variable: "--font-league-spartan-sans",
  subsets: ["latin"],
  weight: ["400", "500"],
});
const montserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${shalimarSans.variable} ${crimsonTextSans.variable} ${leagueSpartanSans.variable} ${montserratSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
